In [1]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np

#series
ser=pd.Series()
print(ser)

#data=np.array(['First','Second','Third','Fourth','Fifth']) #array - homogeneous data in ordered
data=np.array(['java','Python','C','CPP'])
ser=pd.Series(data)
print("Pandas Series \n",ser)


Series([], dtype: object)
Pandas Series 
 0      java
1    Python
2         C
3       CPP
dtype: object


In [2]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr*2)
print(arr**2)

[ 2  4  6  8 10]
[ 1  4  9 16 25]


# numpy - numerical python  provides ndarray object
# N dimensional array objects

# pandas - data analysis and manipulation
# built on numpy package
## provides dataframe as 2d table and series as 1d array
# structured data CSV , Excel ,SQL, JSON

In [3]:
import pandas as pd
import numpy as np

df=pd.DataFrame()
print(df)

data=['First','Second','Third','Fourth','Fifth']
df=pd.DataFrame(data)
print(df)

Empty DataFrame
Columns: []
Index: []
        0
0   First
1  Second
2   Third
3  Fourth
4   Fifth


In [4]:
import pandas as pd
import numpy as np

df=pd.DataFrame()
print(df)

#data=['First','Second','Third','Fourth','Fifth']

data={'Name':['Rahul','Saurav','Steve','Sachin','Virat'],
      'Age':[20,21,22,23,24],
      'degrees':['MBA','MS','CA','BE','B.TECH']}
#print(data,type(data))
df=pd.DataFrame(data)
print(df)

Empty DataFrame
Columns: []
Index: []
     Name  Age degrees
0   Rahul   20     MBA
1  Saurav   21      MS
2   Steve   22      CA
3  Sachin   23      BE
4   Virat   24  B.TECH


In [11]:
import numpy as np

#raw data
products=np.array(['Laptop','Smartphones','Tablets','Headphones','keyboard','Mouse','TV'])
units_sold=np.array([100,150,50,250,300,100,120])
prices=np.array([50000.00,20000.00,25000.00,2000.00,1000.00,500.00,60000.00])

#calculate revenue
revenues=units_sold*prices
print(revenues)


[5000000. 3000000. 1250000.  500000.  300000.   50000. 7200000.]


In [7]:
#find highest revenue
max_index=np.argmax(revenues)
print(max_index)
print('Highest grossing product ',(revenues[max_index]))
#products[0]

6
Highest grossing product  7200000.0


In [9]:
large_quantity=np.argmax(units_sold)
print('Large quantity : index ',large_quantity)
print('Large quantity : value ',(units_sold[large_quantity]))

Large quantity : index  4
Large quantity : value  300


In [5]:
import pandas as pd

#load csv file
data=pd.read_csv("sales.csv")
print(data)


      Product  units_sold  Price
0      Laptop         100  80000
1  Smartphone         250  10000
2      Tablet         150  30000
3  headphones         100   1000


In [6]:
#calculate revenue
data['Revenue']=data['units_sold']*data['Price']
print(data)


      Product  units_sold  Price  Revenue
0      Laptop         100  80000  8000000
1  Smartphone         250  10000  2500000
2      Tablet         150  30000  4500000
3  headphones         100   1000   100000


In [8]:
# loc function is used to access rows and columns by their names not by their index numbers
# df.loc[row_label,column_label]
# idxmax = index(label) of the first occurence of the maximum value in series or dataframe
max_row=data.loc[data['Revenue'].idxmax()]
#print(data)
print(max_row['Product'])
print(max_row['units_sold'])

Laptop
100


In [9]:
import pandas as pd

data={
    'Dept':['HR','ERD','Sales','IT','Finance','ERD','IT'],
    'Salary':[10000,15000,20000,25000,30000,23500,28750],
    'performanceScore':[3.5,4.5,4.1,3.8,4.0,4.8,4.2]
}

df=pd.DataFrame(data,index=['Rahul','Saurav','Steve','Sachin','Virat','Rohit','Rishabh'])
df


Dept  Salary  performanceScore
Rahul         HR   10000               3.5
Saurav       ERD   15000               4.5
Steve      Sales   20000               4.1
Sachin        IT   25000               3.8
Virat    Finance   30000               4.0
Rohit        ERD   23500               4.8
Rishabh       IT   28750               4.2

In [10]:
import pandas as pd

data={
    'Dept':['HR','ERD','Sales','IT','Finance','ERD','IT'],
    'Salary':[10000,15000,20000,25000,30000,23500,28750],
    'performanceScore':[3.5,4.5,4.1,3.8,4.0,4.8,4.2]
}

df=pd.DataFrame(data,index=['ttl101','ttl102','ttl103','tml101','jlr102','jlr103','ttl104'])
df


Dept  Salary  performanceScore
ttl101       HR   10000               3.5
ttl102      ERD   15000               4.5
ttl103    Sales   20000               4.1
tml101       IT   25000               3.8
jlr102  Finance   30000               4.0
jlr103      ERD   23500               4.8
ttl104       IT   28750               4.2

In [11]:
top_performer=df['performanceScore'].idxmax()
top_performer

'jlr103'

In [12]:
df.loc[top_performer]

Dept                  ERD
Salary              23500
performanceScore      4.8
Name: jlr103, dtype: object

In [13]:
# full details of highest paid employee
highest_paid=df['Salary'].idxmax()
print(highest_paid)
df.loc[highest_paid]

jlr102


Dept                Finance
Salary                30000
performanceScore        4.0
Name: jlr102, dtype: object

In [14]:
# list employees from ERD dept
erd_emps=df[df['Dept']=='ERD']
erd_emps


Dept  Salary  performanceScore
ttl102  ERD   15000               4.5
jlr103  ERD   23500               4.8

In [15]:
it_emps=df[df['Dept']=='IT']
top_p=it_emps['performanceScore'].idxmax()
print(top_p)
df.loc[top_p]

ttl104


Dept                   IT
Salary              28750
performanceScore      4.2
Name: ttl104, dtype: object

In [16]:
#products=np.array(['Laptop','Smartphones','Tablets','Headphones','keyboard'])
#units_sold=np.array([100,150,50,250,300])
#prices=np.array([50000.00,20000.00,25000.00,2000.00,1000.00])

import pandas as pd

data=pd.DataFrame(
    {'Month':['Jan','Feb','Mar','Apr','May'],
     'Products':['Laptop','Smartphones','Tablets','Headphones','keyboard'],
      'units_sold':[100,150,50,250,300],
     'Price':[50000.00,20000.00,25000.00,2000.00,1000.00]
    })
print(data)

data['Revenue']=data['units_sold']*data['Price']
data


  Month     Products  units_sold    Price
0   Jan       Laptop         100  50000.0
1   Feb  Smartphones         150  20000.0
2   Mar      Tablets          50  25000.0
3   Apr   Headphones         250   2000.0
4   May     keyboard         300   1000.0


Month     Products  units_sold    Price    Revenue
0   Jan       Laptop         100  50000.0  5000000.0
1   Feb  Smartphones         150  20000.0  3000000.0
2   Mar      Tablets          50  25000.0  1250000.0
3   Apr   Headphones         250   2000.0   500000.0
4   May     keyboard         300   1000.0   300000.0

In [18]:
data.groupby('Products')['Revenue'].sum()


Products
Headphones      500000.0
Laptop         5000000.0
Smartphones    3000000.0
Tablets        1250000.0
keyboard        300000.0
Name: Revenue, dtype: float64

In [19]:
#products=np.array(['Laptop','Smartphones','Tablets','Headphones','keyboard'])
#units_sold=np.array([100,150,50,250,300])
#prices=np.array([50000.00,20000.00,25000.00,2000.00,1000.00])

import pandas as pd

data=pd.DataFrame(
    {'Month':['Jan','Jan','Feb','Feb','Mar','Mar','Mar'],
     'Products':['Laptop','Smartphones','Tablets','Headphones','keyboard','Laptop','Tablets'],
      'units_sold':[100,150,50,250,300,100,300],
     'Price':[50000.00,20000.00,25000.00,2000.00,1000.00,50000.00,15000.00]
    })
print(data)

data['Revenue']=data['units_sold']*data['Price']
data



  Month     Products  units_sold    Price
0   Jan       Laptop         100  50000.0
1   Jan  Smartphones         150  20000.0
2   Feb      Tablets          50  25000.0
3   Feb   Headphones         250   2000.0
4   Mar     keyboard         300   1000.0
5   Mar       Laptop         100  50000.0
6   Mar      Tablets         300  15000.0


Month     Products  units_sold    Price    Revenue
0   Jan       Laptop         100  50000.0  5000000.0
1   Jan  Smartphones         150  20000.0  3000000.0
2   Feb      Tablets          50  25000.0  1250000.0
3   Feb   Headphones         250   2000.0   500000.0
4   Mar     keyboard         300   1000.0   300000.0
5   Mar       Laptop         100  50000.0  5000000.0
6   Mar      Tablets         300  15000.0  4500000.0

In [21]:
data.groupby('Products')['Revenue'].sum()

Products
Headphones       500000.0
Laptop         10000000.0
Smartphones     3000000.0
Tablets         5750000.0
keyboard         300000.0
Name: Revenue, dtype: float64

In [20]:
data.groupby('Month')['Revenue'].sum()

Month
Feb    1750000.0
Jan    8000000.0
Mar    9800000.0
Name: Revenue, dtype: float64

In [21]:
import numpy as np

a=np.array([2,4,5,9,4,7])
b=np.array([5,6,3,6,7,1])

a+b

array([ 7, 10,  8, 15, 11,  8])

In [22]:
#2 4 5 9 4 7 
#5 7 3 6 7 1
import numpy as np

data=np.loadtxt("data.txt")

result=data[0]+data[1]
result

array([ 7., 11.,  8., 15., 11.,  8.])

In [23]:
import pandas as pd
#load csv file
data=pd.read_csv("sales_transpose.csv")
print(data)

      product  laptop  smartphone  tablet  headphones
0  units_sold     100         250     150         100
1       Price   80000       10000   30000        1000


In [24]:
data.set_index('product')
#data.set_index('units_sold')
#data.set_index('Price')
data

product  laptop  smartphone  tablet  headphones
0  units_sold     100         250     150         100
1       Price   80000       10000   30000        1000

In [35]:
import pandas as pd
#load csv file
data=pd.read_csv("sales_transpose.csv")
print(data)

data_t=data.T
df=pd.DataFrame(data_t)
df

      product  laptop  smartphone  tablet  headphones
0  units_sold     100         250     150         100
1       Price   80000       10000   30000        1000


0      1
product     units_sold  Price
laptop             100  80000
smartphone         250  10000
tablet             150  30000
headphones         100   1000

In [36]:
df.columns=df.iloc[0]
df

product     units_sold  Price
product     units_sold  Price
laptop             100  80000
smartphone         250  10000
tablet             150  30000
headphones         100   1000

In [38]:
df=df[1:]
df

product    units_sold  Price
laptop            100  80000
smartphone        250  10000
tablet            150  30000
headphones        100   1000

In [49]:
df['revenue']=df['units_sold']*df['Price']
df

C:\Users\gbb919982\AppData\Local\Temp\ipykernel_27404\3732904393.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['revenue']=df['units_sold']*df['Price']


product    units_sold  Price  revenue  Revenue
laptop            100  80000  8000000  8000000
smartphone        250  10000  2500000  2500000
tablet            150  30000  4500000  4500000
headphones        100   1000   100000   100000

In [45]:
#calculate revenue
data=df
max_row=data.loc[data['Revenue'].idxmax()]
print(data)
max_row
#print(max_row['product'])
#print(max_row['units_sold'])

product    units_sold  Price  revenue  Revenue
laptop            100  80000  8000000  8000000
smartphone        250  10000  2500000  2500000
tablet            150  30000  4500000  4500000
headphones        100   1000   100000   100000


product
units_sold        100
Price           80000
revenue       8000000
Revenue       8000000
Name: laptop, dtype: object

In [50]:

import pandas as pd
import numpy as np

# Load CSV
data = pd.read_csv("sales_transpose.csv")

# Set 'product' as index and transpose
data_t = data.set_index('product').T
print("\nCorrect Transposed Data:")
print(data_t)

# Calculate revenue
data_t['revenue'] = data_t['units_sold'].astype(int) * data_t['Price'].astype(int)
print("\nData with Revenue:")
print(data_t)



Correct Transposed Data:
product     units_sold  Price
laptop             100  80000
smartphone         250  10000
tablet             150  30000
headphones         100   1000

Data with Revenue:
product     units_sold  Price  revenue
laptop             100  80000  8000000
smartphone         250  10000  2500000
tablet             150  30000  4500000
headphones         100   1000   100000


In [51]:
max_row=data_t.loc[data_t['revenue'].idxmax()]
print(data)
max_row

      product  laptop  smartphone  tablet  headphones
0  units_sold     100         250     150         100
1       Price   80000       10000   30000        1000


product
units_sold        100
Price           80000
revenue       8000000
Name: laptop, dtype: int64